services:
  postgres:
    image: postgres:16
    container_name: postgres_redsocial
    environment:
      POSTGRES_DB: red_social_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:7
    container_name: mongo_redsocial
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: redis_redsocial
    ports:
      - "6379:6379"

  cassandra:
    image: cassandra:5
    container_name: cassandra_redsocial
    ports:
      - "9042:9042"
